### ISSUE TITLE
what is `pimg`?

### ISSUE THREAD

**Issue by psteinb** [colemanbroad/ndtess#7]
in test_voronoi.py, I see:
```
img = io.imread(path.join(test_resources_dir, 'microtubule foams.jpg'))
pimg = np.load(path.join(test_resources_dir, 'microtubule foams_Probabilities Stage 2.npy'))
vorimg = io.imread(path.join(test_resources_dir, 'vorimg.tif'))
pimg = pimg.astype('float16')
distimg = pimg[:,:,1].copy().astype('float32')
distimg = gaussian(distimg, 30)
bimg = pimg[...,0] > 0.9
lab, nc = label(bimg)
```
what is the role of `pimg` here? and what does it contain? 

I suggest to start with a synthetic image of smaller size so that I can understand the requirements of the API better. For this, I need to understand the minimal requirements to invoke `tessellate_labimg`.

**Comment by colemanbroad** [comment]
Hey Peter sorry for the late response.

pimg is the name for a probability map. It is the result of running a pixelwise classifier on `img` to highlight different classes of objects. In this case the third index has three channels which correspond to three different object classes: round dots, membrane boundaries, and background [in that order]. Here it’s used to build the metric field `distimg` and the binary mask `bimg` which is used to segment and label objects (the dots) and use them for seeding the algorithm.

As far as the interface is concerned, there is really only one function that’s important: tesselations.tessellate_labimg
and it’s tested in test_tessellate_labimg

Can I drop by sometime this afternoon? We can take a quick look at the code together.

cheers,
Coleman
